export let CATEGORIES = [
  "Landscape",
  "Portrait",
  "Abstract",
  "Wildlife",
  "Cityscape",
  "Macro",
  "Street Photography",
  "Astrophotography",
  "Black and White",
  "Underwater",
  "Fashion",
  "Food",
  "Sports",
  "Architecture",
  "Travel",
  "Fine Art",
  "Wedding",
  "Product",
  "Event",
  "Nature",
];
